"""
THIS MODULE SETS UP CONSTANTS TO BE IMPORTED FOR USE IN OTHER MODULES WITHIN THE PROGRAM

"""

SCREEN_WIDTH = 720
SCREEN_HEIGHT = 500

PLAYER_RAQUET_HEIGHT = 100
PLAYER_RAQUET_WIDTH = 25
PLAYER_SPEED = 300
PLAYER_START_POSITION_X = 20
PLAYER_START_POSITION_Y = SCREEN_HEIGHT/2

NET_HEIGHT = SCREEN_HEIGHT
NET_WIDTH = 2

BALL_RADIUS = 10
BALL_SPEED = 100